frontend:
  replicas: 1
  image: origenai/cloud-engineer-test-sample-app-frontend:1.0.0
  port: 3000

api:
  replicas: 1
  image: origenai/cloud-engineer-test-sample-app-backend:1.0.0  # This is now the api service
  port: 3001
  mongoUri: "mongodb://mongo:27017"
  username: "username"
  password: "password"

mongo:
  image: mongo
  username: "username"
  password: "password"
  volume: mmongo-pvc
