apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
data:
  MONGODB_INITDB_ROOT_USERNAME: {{ .Values.mongo.username | b64enc }}
  MONGODB_INITDB_ROOT_PASSWORD: {{ .Values.mongo.password | b64enc }}
